# Generated by Django 2.0 on 2017-12-04 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praisal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisement',
            old_name='uuid',
            new_name='slug',
        ),
    ]
