# Generated by Django 2.0 on 2017-12-05 17:04

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('praisal', '0003_auto_20171204_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisement',
            name='content',
        ),
        migrations.AddField(
            model_name='appraisement',
            name='bad_lines',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='appraisement',
            name='parsed_content',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='appraisement',
            name='prices',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='appraisement',
            name='code',
            field=models.TextField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='appraisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
    ]
